# Generated by Django 3.1.5 on 2021-01-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cet6',
            field=models.BooleanField(default=False, verbose_name='通过CET6'),
        ),
    ]
