# Generated by Django 3.1.5 on 2021-01-29 19:51

from django.db import migrations, models
import polls.utils


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='person_id',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[polls.utils.IDValidator], verbose_name='身份证号'),
        ),
    ]
