# Generated by Django 3.1.5 on 2021-01-26 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='number',
            field=models.IntegerField(blank=True, verbose_name='工号/学号'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, '请输入11位有效电话')], verbose_name='电话'),
        ),
    ]
