# Generated by Django 3.1.5 on 2021-01-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210126_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='工号/学号'),
        ),
    ]
