# Generated by Django 3.1.5 on 2021-01-30 21:29

from django.db import migrations, models
import django.utils.timezone
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210131_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anoucement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('content', django_summernote.fields.SummernoteTextField(null=True, verbose_name='内容')),
                ('last_edit_timestamp', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('public_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='公布时间')),
            ],
            options={
                'verbose_name': '公告',
            },
        ),
        migrations.AlterField(
            model_name='myuser',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='工号/学号'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='major_student_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='本科专业总人数'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='本科专业内学分绩排名'),
        ),
    ]
