# Generated by Django 3.1.5 on 2021-04-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_resume_cet6_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='tutor',
            field=models.CharField(blank=True, max_length=16, verbose_name='意向导师'),
        ),
    ]
