# Generated by Django 3.1.5 on 2021-02-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210131_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='submitted',
            field=models.BooleanField(default=False, verbose_name='是否已提交'),
        ),
    ]
