# Generated by Django 3.1.5 on 2021-01-26 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210126_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, choices=[('天津', [('4112010055', '南开大学')]), ('北京', [('4111010003', '清华大学'), ('4111010001', '北京大学'), ('4111010007', '北京理工大学')])], max_length=16, verbose_name='学校')),
                ('school', models.CharField(blank=True, max_length=16, verbose_name='学院')),
                ('major', models.CharField(blank=True, max_length=16, verbose_name='本科主修专业')),
                ('gpa', models.FloatField(blank=True, verbose_name='百分制学分绩')),
                ('rank', models.SmallIntegerField(blank=True, verbose_name='本科专业内学分绩排名')),
                ('major_student_amount', models.IntegerField(blank=True, verbose_name='本科专业总人数')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生账号')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
            },
        ),
    ]
