# Generated by Django 3.1.5 on 2021-01-27 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.MinLengthValidator(11, '请输入11位有效电话')], verbose_name='电话'),
        ),
    ]
