# Generated by Django 3.1.6 on 2021-04-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_resume_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='aspiration',
            field=models.CharField(blank=True, choices=[(0, '专硕'), (1, '学硕'), (2, '直博')], max_length=16, verbose_name='志愿'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='major_choices',
            field=models.CharField(blank=True, choices=[(0, '统计学'), (1, '应用统计')], max_length=16, verbose_name='研究生报名专业'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='tutor',
            field=models.CharField(blank=True, max_length=16, verbose_name='直博生意向导师'),
        ),
    ]
