# Generated by Django 3.1.5 on 2021-02-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_resume_submitted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='anoucement',
            index=models.Index(fields=['-public_time'], name='polls_anouc_public__572fbb_idx'),
        ),
    ]
