# Generated by Django 3.1.6 on 2021-04-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210402_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='tutor',
            field=models.CharField(blank=True, choices=[(0, '王兆军'), (1, '刘民千'), (2, '邹长亮')], max_length=16, verbose_name='直博生意向导师'),
        ),
    ]
