# Generated by Django 3.1.5 on 2021-02-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210203_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anoucement',
            options={'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': '简历', 'verbose_name_plural': '简历'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='工号'),
        ),
    ]
