# Generated by Django 3.1.6 on 2021-04-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210403_0804'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='announcement',
            name='polls_anouc_public__572fbb_idx',
        ),
        migrations.AlterField(
            model_name='resume',
            name='tutor',
            field=models.CharField(blank=True, choices=[(0, '王兆军'), (1, '刘民千'), (2, '邹长亮'), (3, '周永道'), (4, '杨建峰'), (5, '胡刚'), (6, '徐铣明'), (7, '王磊'), (8, '马志明'), (9, '刘伟')], max_length=16, verbose_name='直博生意向导师'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['-public_time'], name='polls_annou_public__a5bfa4_idx'),
        ),
    ]
