# Generated by Django 3.1.6 on 2021-04-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210404_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='major_choices',
        ),
        migrations.AlterField(
            model_name='resume',
            name='aspiration',
            field=models.CharField(blank=True, choices=[(0, '专硕（应用统计专业）'), (1, '学硕（统计学专业）'), (2, '直博（统计学专业）')], max_length=16, verbose_name='志愿'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='cet6',
            field=models.BooleanField(default=False, verbose_name='通过cet6'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='other_prize_penalty',
            field=models.TextField(blank=True, max_length=1024, verbose_name='与数学或建模相关奖项'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='others',
            field=models.TextField(blank=True, max_length=1024, verbose_name='其他获奖（包括奖学金）'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='tutor',
            field=models.CharField(blank=True, choices=[(0, '王兆军'), (1, '刘民千'), (2, '邹长亮'), (3, '周永道'), (4, '杨建峰'), (5, '胡刚'), (6, '徐铣明'), (7, '王磊'), (8, '马志明'), (9, '刘伟')], max_length=16, verbose_name='意向导师'),
        ),
    ]
