# Generated by Django 3.1.5 on 2021-02-04 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_resume_special_permit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='建议得分')),
                ('rank', models.IntegerField(blank=True, default=0, verbose_name='建议排名')),
                ('admiss', models.BooleanField(default=False, verbose_name='录取')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.resume', verbose_name='对应简历')),
            ],
            options={
                'verbose_name': '简历评定',
                'verbose_name_plural': '简历评定',
            },
        ),
    ]
