# Generated by Django 3.1.6 on 2021-04-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210407_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='cet6_grades',
            new_name='cet6_score',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='aspiration',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='tutor',
        ),
        migrations.AddField(
            model_name='resume',
            name='enrollment_major',
            field=models.CharField(choices=[('统计学', '统计学'), ('应用统计', '应用统计')], default='', max_length=10, verbose_name='报考专业'),
        ),
        migrations.AddField(
            model_name='resume',
            name='enrollment_tutor',
            field=models.CharField(blank=True, max_length=20, verbose_name='意向导师'),
        ),
        migrations.AddField(
            model_name='resume',
            name='enrollment_type',
            field=models.CharField(choices=[('Master', '硕士'), ('DDS', '直博生')], default='', max_length=6, verbose_name='招生类型'),
        ),
    ]
