# Generated by Django 3.1.5 on 2021-02-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_resumeresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='models/', verbose_name='模型文件')),
                ('name', models.CharField(max_length=16, verbose_name='模型名称')),
                ('version', models.CharField(blank=True, default='v1.0', max_length=16, verbose_name='版本号')),
            ],
            options={
                'verbose_name': '模型',
                'verbose_name_plural': '模型',
                'unique_together': {('name', 'version')},
            },
        ),
    ]
